package panels.dialog;

import connection.MySQL;
import gui.MainInterface;
import java.awt.Color;
import javax.swing.BorderFactory;
import util.OptionPane;
import util.RoundedUtil;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Level;
import util.LoggerUtil;

/**
 *
 * @author mgssr
 */
public class AttendanceDialog extends javax.swing.JDialog {

    private static final Logger logger = LoggerUtil.getLogger(AttendanceDialog.class);

    /**
     * Creates new form AttendanceDialog
     *
     * @param parent
     * @param modal
     */
    public AttendanceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initCustomizations();
    }

    private void initCustomizations() {
        setPaddings();
        setBorderRadius();
    }

    private void setPaddings() {
        int p1 = 20;
        int p2 = 50;
        jPanel2.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
        jPanel3.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
        markedLabel.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
        statusLabel.setBorder(BorderFactory.createEmptyBorder(p2, p2, p2, p2));
    }

    private void setBorderRadius() {
        int radius = 15;
        RoundedUtil.roundedCorners(idField, radius);
        RoundedUtil.roundedCorners(statusLabel, radius);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        markedLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 620));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARK ATTENDANCE");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Enter Your ID");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setPreferredSize(new java.awt.Dimension(68, 32));
        jPanel4.add(jLabel2);

        idField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        idField.setPreferredSize(new java.awt.Dimension(68, 65));
        jPanel4.add(idField);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        markedLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        markedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        markedLabel.setText(" ");
        jPanel5.add(markedLabel, java.awt.BorderLayout.NORTH);

        statusLabel.setOpaque(true);
        jPanel5.add(statusLabel, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        confirmBtn.setBackground(new java.awt.Color(255, 100, 0));
        confirmBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        confirmBtn.setText("CONFIRM");
        confirmBtn.setBorderPainted(false);
        confirmBtn.setPreferredSize(new java.awt.Dimension(80, 55));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel3.add(confirmBtn);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        markAttendance();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void markAttendance() {
        String id = idField.getText().trim();
        Color successColor = new Color(0, 255, 0);
        Color dangerColor = new Color(255, 51, 51);
        Color warningColor = new Color(255, 255, 51);

        String query1 = "INSERT INTO `gms`.`member_attendance` (`member_member_id`) "
                + "VALUES (" + id + ");";

        String query2 = "SELECT `payment_status` FROM `gms`.`member` WHERE `member_id` = " + id + ";";

        String query3 = "SELECT * "
                + "FROM `gms`.`member_attendance` "
                + "WHERE `member_member_id` = '" + id + "' AND `date` >= NOW() - INTERVAL 1 DAY;";

        try {
            ResultSet rs_1 = MySQL.executeSearch(query3);
            if (rs_1.next()) {
                markedLabel.setForeground(warningColor);
                markedLabel.setText("Already Marked In Last 24 Hours");
            } else {
                boolean executeQuery1 = MySQL.executeIUD(query1);
                if (executeQuery1 && MySQL.getAffectedRows() != 0) {
                    markedLabel.setForeground(successColor);
                    markedLabel.setText("Attendance Marked");

                    MainInterface.getInstance().refreshAttendanceData();

                    try {
                        ResultSet rs_2 = MySQL.executeSearch(query2);
                        if (rs_2.next()) {
                            if (rs_2.getBoolean("payment_status")) {
                                statusLabel.setBackground(successColor);
                            } else {
                                statusLabel.setBackground(dangerColor);
                            }
                        }
                    } catch (SQLException e) {
                        logger.log(Level.SEVERE, "AttendanceDialog.markAttendance(){} - rs_2 caused an error!", e);
                    }
                } else {
                    OptionPane.showMessage(this, "Warning Message", "Something Went Wrong! Try Again.    ", "WARNING");
                }
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "AttendanceDialog.markAttendance(){} - rs_1 caused an error!", e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AttendanceDialog dialog = new AttendanceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel markedLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
