package gui;

import connection.MySQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import util.RoundedUtil;
import java.util.logging.Logger;
import java.util.logging.Level;
import panels.dialog.AttendanceDialog;
import util.AppIconUtil;
import util.LoggerUtil;
import util.OptionPane;

/**
 *
 * @author mgssr
 */
public class LoginForm extends javax.swing.JFrame {

    private static final Logger logger = LoggerUtil.getLogger(LoginForm.class);
    public static Thread attendanceThread;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        initCustomizations();
    }

    private void initCustomizations() {
        AppIconUtil.applyIcon(this);
        setPaddings();
        setBorderRadius();
    }

    private void setPaddings() {
        int p1 = 20;
        formPanel.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
        btnPanel.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
    }

    private void setBorderRadius() {
        int radius = 15;
        RoundedUtil.roundedCorners(usernameField, radius);
        RoundedUtil.roundedCorners(passwordField, radius);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        btnPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 620));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FITNESS CENTER LOGIN");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        formPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        formPanel.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Username Or Mobile");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        formPanel.add(jLabel2);

        usernameField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        formPanel.add(usernameField);

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        formPanel.add(jLabel3);
        formPanel.add(passwordField);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        btnPanel.setLayout(new java.awt.GridLayout(1, 0));

        loginBtn.setBackground(new java.awt.Color(255, 100, 0));
        loginBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        loginBtn.setText("LOG IN");
        loginBtn.setBorderPainted(false);
        loginBtn.setPreferredSize(new java.awt.Dimension(80, 55));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        btnPanel.add(loginBtn);

        getContentPane().add(btnPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        logIn();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void logIn() {
        String username = usernameField.getText().trim();
        String pass = passwordField.getText().trim();

        String query = "SELECT * FROM `admin` LEFT JOIN `status` ON `status_id` = `status_status_id` WHERE "
                + "(`username` = '" + username + "' OR `mobile` = '" + username + "') AND "
                + "`password` = '" + pass + "';";

        try {
            ResultSet rs = MySQL.executeSearch(query);

            if (rs.next()) {
                if (rs.getBoolean("status_status")) {
                    this.dispose();
                    MainInterface.getInstance().setVisible(true);
                    attendanceThread = new Thread(() -> {
                        new AttendanceDialog(null, false).setVisible(true);
                    });
                    attendanceThread.start();
                } else {
                    OptionPane.showMessage(this, "Error Message", "User Access Has Been Deactivated!.    ", "ERROR");
                }
            } else {
                OptionPane.showMessage(this, "Error Message", "Invalid Credentials! Try Again.    ", "ERROR");
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "LoginForm.logIn() caused an error!", e);
            OptionPane.showMessage(this, "Error Message", "Database Connection Error!    ", "ERROR");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
