package gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import javax.swing.BorderFactory;
import util.RoundedUtil;
import java.util.logging.Logger;
import java.util.logging.Level;
import util.AppIconUtil;
import util.LoggerUtil;

/**
 *
 * @author mgssr
 */
public class SplashSceen extends javax.swing.JFrame {

    private static final Logger logger = LoggerUtil.getLogger(SplashSceen.class);

    /**
     * Creates new form SplashSceen
     */
    public SplashSceen() {
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        initCustomizations();
        loadingAnimation();
    }

    private void initCustomizations() {
        AppIconUtil.applyIcon(this);
        setPaddings();
        setBorderRadius();
    }

    private void setBorderRadius() {
        RoundedUtil.roundedCorners(bgLabel, 20);
        RoundedUtil.roundedCorners(loadingBar, 10);
    }

    private void setPaddings() {
        int p1 = 10;
        jPanel1.setBorder(BorderFactory.createEmptyBorder(p1, p1, p1, p1));
    }

    private void loadingAnimation() {
        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                loadingBar.setValue(i);
                if (i == 10) {
                    i = 22;
                }
                if (i == 49) {
                    i = 78;
                }
                if (i == 70) {
                    i = 95;
                }
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    logger.log(Level.SEVERE, "loading animation caused an error!", e);
                }
            }
            this.dispose();
            new LoginForm().setVisible(true);
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym Management System");
        setMinimumSize(null);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FITNESS    ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 100, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("     CENTER");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        loadingBar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loadingBar.setForeground(new java.awt.Color(255, 102, 102));
        loadingBar.setPreferredSize(new java.awt.Dimension(140, 30));
        loadingBar.setStringPainted(true);
        jPanel1.add(loadingBar, java.awt.BorderLayout.SOUTH);

        bgLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 100, 0), 1, true));
        bgLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bgLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bgLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacDarkLaf.setup();
//        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashSceen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar loadingBar;
    // End of variables declaration//GEN-END:variables
}
