package panels;

import java.sql.Connection;
import connection.MySQL;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.OptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import util.LoggerUtil;

/**
 *
 * @author mgssr
 */
public class GenerateReportsPanel extends javax.swing.JPanel {

    private final Connection connection;
    private final HashMap<String, Object> parameters;

    private static final Logger logger = LoggerUtil.getLogger(GenerateReportsPanel.class);

    /**
     * Creates new form GenerateReportsPanel
     */
    public GenerateReportsPanel() {
        initComponents();
        connection = MySQL.getConnection();
        parameters = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        memberReportBtn = new javax.swing.JButton();
        trainerReportBtn = new javax.swing.JButton();
        attendanceReportBtn = new javax.swing.JButton();
        paymentReportBtn = new javax.swing.JButton();
        productSalesReport = new javax.swing.JButton();
        equipmentReportBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        backupBtn = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        memberReportBtn.setBackground(new java.awt.Color(189, 189, 189));
        memberReportBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        memberReportBtn.setForeground(new java.awt.Color(22, 22, 22));
        memberReportBtn.setText("Members Report");
        memberReportBtn.setMinimumSize(new java.awt.Dimension(80, 40));
        memberReportBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        memberReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberReportBtnActionPerformed(evt);
            }
        });
        jPanel5.add(memberReportBtn);

        trainerReportBtn.setBackground(memberReportBtn.getBackground());
        trainerReportBtn.setFont(memberReportBtn.getFont());
        trainerReportBtn.setForeground(memberReportBtn.getForeground());
        trainerReportBtn.setText("Trainer Report");
        trainerReportBtn.setMinimumSize(new java.awt.Dimension(80, 40));
        trainerReportBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        trainerReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerReportBtnActionPerformed(evt);
            }
        });
        jPanel5.add(trainerReportBtn);

        attendanceReportBtn.setBackground(memberReportBtn.getBackground());
        attendanceReportBtn.setFont(memberReportBtn.getFont());
        attendanceReportBtn.setForeground(memberReportBtn.getForeground());
        attendanceReportBtn.setText("Attendance Report");
        attendanceReportBtn.setMinimumSize(new java.awt.Dimension(80, 40));
        attendanceReportBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        attendanceReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceReportBtnActionPerformed(evt);
            }
        });
        jPanel5.add(attendanceReportBtn);

        paymentReportBtn.setBackground(memberReportBtn.getBackground());
        paymentReportBtn.setFont(memberReportBtn.getFont());
        paymentReportBtn.setForeground(memberReportBtn.getForeground());
        paymentReportBtn.setText("Payments Report");
        paymentReportBtn.setMinimumSize(new java.awt.Dimension(80, 40));
        paymentReportBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        paymentReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentReportBtnActionPerformed(evt);
            }
        });
        jPanel5.add(paymentReportBtn);

        productSalesReport.setBackground(memberReportBtn.getBackground());
        productSalesReport.setFont(memberReportBtn.getFont());
        productSalesReport.setForeground(memberReportBtn.getForeground());
        productSalesReport.setText("Product Sales Report");
        productSalesReport.setMinimumSize(new java.awt.Dimension(80, 40));
        productSalesReport.setPreferredSize(new java.awt.Dimension(200, 40));
        productSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSalesReportActionPerformed(evt);
            }
        });
        jPanel5.add(productSalesReport);

        equipmentReportBtn.setBackground(memberReportBtn.getBackground());
        equipmentReportBtn.setFont(memberReportBtn.getFont());
        equipmentReportBtn.setForeground(memberReportBtn.getForeground());
        equipmentReportBtn.setText("Equipment Report");
        equipmentReportBtn.setMinimumSize(new java.awt.Dimension(80, 40));
        equipmentReportBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        equipmentReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentReportBtnActionPerformed(evt);
            }
        });
        jPanel5.add(equipmentReportBtn);

        jPanel2.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        add(jPanel2);

        backupBtn.setBackground(new java.awt.Color(22, 22, 22));
        backupBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        backupBtn.setForeground(new java.awt.Color(189, 189, 189));
        backupBtn.setText("Backup Data");
        backupBtn.setRolloverEnabled(false);
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(backupBtn))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 539, Short.MAX_VALUE)
                .addComponent(backupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void memberReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberReportBtnActionPerformed
        generateReport("gms_member_report.jasper");
    }//GEN-LAST:event_memberReportBtnActionPerformed

    private void attendanceReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceReportBtnActionPerformed
        generateReport("gms_member_attendance_report.jasper");
    }//GEN-LAST:event_attendanceReportBtnActionPerformed

    private void productSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSalesReportActionPerformed
        generateReport("gms_product_sales_report.jasper");
    }//GEN-LAST:event_productSalesReportActionPerformed

    private void trainerReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerReportBtnActionPerformed
        generateReport("gms_trainer_report.jasper");
    }//GEN-LAST:event_trainerReportBtnActionPerformed

    private void paymentReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentReportBtnActionPerformed
        generateReport("gms_payments_report.jasper");
    }//GEN-LAST:event_paymentReportBtnActionPerformed

    private void equipmentReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentReportBtnActionPerformed
        generateReport("gms_equipment_report.jasper");
    }//GEN-LAST:event_equipmentReportBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        backupBtn.setEnabled(false);
        new Thread(() -> {
            if (MySQL.backupDatabase()) {
                OptionPane.showMessage(null, "Message", "Backup File Created Successfully!    ", "INFORMATION");
                backupBtn.setEnabled(true);
            } else {
                OptionPane.showMessage(null, "Error Message", "Could Not Create Backup File!    ", "ERROR");
                backupBtn.setEnabled(true);
            }
        }).start();
    }//GEN-LAST:event_backupBtnActionPerformed

    private void generateReport(String fileName) {
        try {
            InputStream filePath = getClass()
                    .getClassLoader()
                    .getResourceAsStream("report/" + fileName);

            if (filePath == null) {
                throw new FileNotFoundException("Report file not found: report/" + fileName);
            }

            // Fill the report
            JasperPrint filledReport = JasperFillManager.fillReport(filePath, parameters, connection);

            // Display the report
            JasperViewer.viewReport(filledReport, false);

        } catch (FileNotFoundException | JRException e) {
            OptionPane.showMessage(this, "Error Message", "Error Generating Report! Try Again.    ", "ERROR");
            logger.log(Level.SEVERE, "GenerateReportsPanel.generateReport(){} caused an error!", e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendanceReportBtn;
    private javax.swing.JButton backupBtn;
    private javax.swing.JButton equipmentReportBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton memberReportBtn;
    private javax.swing.JButton paymentReportBtn;
    private javax.swing.JButton productSalesReport;
    private javax.swing.JButton trainerReportBtn;
    // End of variables declaration//GEN-END:variables
}
