package panels;

import connection.MySQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import util.RoundedUtil;
import java.util.logging.Logger;
import java.util.logging.Level;
import util.LoggerUtil;

/**
 *
 * @author mgssr
 */
public class WorkoutPlansPanel extends javax.swing.JPanel {

    public static String totalPlansCount;
    public static String beginnerPlansCount;
    public static String intermediatePlansCount;
    public static String advancedPlansCount;

    private static final Logger logger = LoggerUtil.getLogger(WorkoutPlansPanel.class);

    /**
     * Creates new form WorkoutPlansPanel
     */
    public WorkoutPlansPanel() {
        initComponents();
        initCustomizations();
        initPanelData();
    }

    private void initCustomizations() {
        setPaddings();
        setBorderRadius();
    }

    private void setPaddings() {
        statsPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    }

    private void setBorderRadius() {
        int radius = 15;

        RoundedUtil.roundedCorners(searchTextField, radius);
        RoundedUtil.roundedCorners(statsPanel, radius);
        RoundedUtil.roundedCorners(tableScrollPane, radius);
    }

//    ----------------------------------
    private void initPanelData() {
        setTableData();
        setStatsPanelData();
    }

    private void setTableData() {
        String query = "SELECT * FROM workout_plan";

        try {
            DefaultTableModel dtm = (DefaultTableModel) membersTable.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MySQL.executeSearch(query);

            while (rs.next()) {
                Vector<String> dataRow = new Vector();
                dataRow.add(rs.getString("plan_id"));
                dataRow.add(rs.getString("level"));
                dataRow.add(rs.getString("day1"));
                dataRow.add(rs.getString("day2"));
                dataRow.add(rs.getString("day3"));
                dataRow.add(rs.getString("day4"));
                dataRow.add(rs.getString("day5"));
                dataRow.add(rs.getString("day6"));
                dataRow.add(rs.getString("day7"));

                dtm.addRow(dataRow);
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "WorkoutPlansPanel.setTableData(){} caused an error!", e);
        }
    }

    private void setStatsPanelData() {
        String query = "SELECT "
                + "COUNT(*) AS total_plans, "
                + "COUNT(CASE WHEN level=\"BEGINNER\" THEN 1 ELSE NULL END) AS beginner_plans, "
                + "COUNT(CASE WHEN level=\"INTERMEDIATE\" THEN 1 ELSE NULL END) AS intermediate_plans, "
                + "COUNT(CASE WHEN level=\"ADVANCED\" THEN 1 ELSE NULL END) AS advanced_plans "
                + "FROM workout_plan;";

        try {
            ResultSet rs = MySQL.executeSearch(query);

            if (rs.next()) {
                totalPlansCount = String.format("%02d", rs.getInt("total_plans"));
                beginnerPlansCount = String.format("%02d", rs.getInt("beginner_plans"));
                intermediatePlansCount = String.format("%02d", rs.getInt("intermediate_plans"));
                advancedPlansCount = String.format("%02d", rs.getInt("advanced_plans"));
            }
            noOfPlansLabel.setText("No of Plans:  " + totalPlansCount);
            beginnerPlansLabel.setText("Beginner Level Plans:  " + beginnerPlansCount);
            intermediatePlansLabel.setText("Intermediate Level Plans:  " + intermediatePlansCount);
            advancedPlansLabel.setText("Advanced Level Plans:  " + advancedPlansCount);
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "WorkoutPlansPanel.setStatsPanelData(){} caused an error!", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        manageBtn = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        noOfPlansLabel = new javax.swing.JLabel();
        intermediatePlansLabel = new javax.swing.JLabel();
        beginnerPlansLabel = new javax.swing.JLabel();
        advancedPlansLabel = new javax.swing.JLabel();
        psudoLabel1 = new javax.swing.JLabel();
        psudoLabel2 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        membersTable = new javax.swing.JTable();

        topPanel.setBackground(new java.awt.Color(153, 255, 255));
        topPanel.setOpaque(false);
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 45));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        searchTextField.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(204, 204, 204));
        searchTextField.setToolTipText("");
        jPanel1.add(searchTextField);

        topPanel.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        searchBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn);

        manageBtn.setBackground(new java.awt.Color(255, 100, 0));
        manageBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        manageBtn.setText("Manage");
        manageBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel2.add(manageBtn);

        topPanel.add(jPanel2);

        statsPanel.setBackground(new java.awt.Color(51, 51, 51));
        statsPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        noOfPlansLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        noOfPlansLabel.setText("No of Plans:");
        statsPanel.add(noOfPlansLabel);

        intermediatePlansLabel.setFont(noOfPlansLabel.getFont());
        intermediatePlansLabel.setText("Intermediate Level Plans:");
        statsPanel.add(intermediatePlansLabel);

        beginnerPlansLabel.setFont(noOfPlansLabel.getFont());
        beginnerPlansLabel.setText("Beginner Level Plans:");
        statsPanel.add(beginnerPlansLabel);

        advancedPlansLabel.setFont(noOfPlansLabel.getFont());
        advancedPlansLabel.setText("Advanced Level Plans:");
        statsPanel.add(advancedPlansLabel);

        psudoLabel1.setFont(noOfPlansLabel.getFont());
        statsPanel.add(psudoLabel1);

        psudoLabel2.setFont(noOfPlansLabel.getFont());
        statsPanel.add(psudoLabel2);

        membersTable.setAutoCreateRowSorter(true);
        membersTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        membersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LEVEL", "DAY 01", "DAY 02", "DAY 03", "DAY 04", "DAY 05", "DAY 06", "DAY 07"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        membersTable.setShowGrid(true);
        tableScrollPane.setViewportView(membersTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(topPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        getSearchResult();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void getSearchResult() {
        String searchText = searchTextField.getText();

        if (!searchText.isBlank()) {
            searchTableData("%" + searchText + "%");
        } else {
            setTableData();
        }
    }

    private void searchTableData(String searchText) {
        String query = "SELECT * FROM workout_plan "
                + "WHERE "
                + "plan_id LIKE '" + searchText + "';";

        try {
            DefaultTableModel dtm = (DefaultTableModel) membersTable.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MySQL.executeSearch(query);

            while (rs.next()) {
                Vector<String> dataRow = new Vector();
                dataRow.add(rs.getString("plan_id"));
                dataRow.add(rs.getString("level"));
                dataRow.add(rs.getString("day1"));
                dataRow.add(rs.getString("day2"));
                dataRow.add(rs.getString("day3"));
                dataRow.add(rs.getString("day4"));
                dataRow.add(rs.getString("day5"));
                dataRow.add(rs.getString("day6"));
                dataRow.add(rs.getString("day7"));

                dtm.addRow(dataRow);
            }
        } catch (SQLException e) {
            logger.log(Level.SEVERE, "WorkoutPlansPanel.searchTableData(){} caused an error!", e);
        }
    }

    public void refreshData() {
        setTableData();
        setStatsPanelData();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancedPlansLabel;
    private javax.swing.JLabel beginnerPlansLabel;
    private javax.swing.JLabel intermediatePlansLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton manageBtn;
    private javax.swing.JTable membersTable;
    private javax.swing.JLabel noOfPlansLabel;
    private javax.swing.JLabel psudoLabel1;
    private javax.swing.JLabel psudoLabel2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
